### ISSUE TITLE
Opening the raw file during the acquisition

### ISSUE THREAD

**Issue by heejongkim** [thermofisherlsms/xcalibur-workbench#3]
Hello,

This is something that was observed between different Mass specs (QE and Lumos) and different Browsers (Qual Browser and FreeStyle). When I tried to open "InAcquisition" raw file with Qual Browser on QE, I generally had no problem with it but, on Lumos, Qual Browser wouldn't be able to open it while FreeStyle can open it. So, I tried it with Xcalibur workbench to open up "InAcquisition" raw file but, so far, I had no luck. 
Is there any specific technical barriers that only FreeStyle can handle "InAcquisition" Lumos raw file while others cannot? Or, is there a plan to support this in Xcalibur-Workbench in the future?

Thanks,
Hee Jong

**Comment by MichaelSenko** [comment]
Hi Hee Jong,

I can't think of what would cause different behavior between the two instruments.  Are they running the same version of Xcalibur and Foundation?

Thanks
Mike

**Comment by dbaileychess** [comment]
Hi Hee Jong,

 I think this question is better suited for the other lua raw file repo. I am going to close it here and can you reopen it there?
